# Generated by Django 4.1.1 on 2022-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_is_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="is_favourite",
            field=models.BooleanField(blank=True, null=True, verbose_name="Favourite?"),
        ),
    ]
