# Generated by Django 4.1.1 on 2022-12-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                help_text="150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                verbose_name="username",
            ),
        ),
    ]
