# Generated by Django 4.1.1 on 2022-10-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_contact_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="password",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="username",
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
